-- Select the programs (curso) that have classes with all the existing types.
-- There are 5 types

-- x environment
SELECT CURSO
FROM XOCORRENCIAS
    INNER JOIN XUCS USING (CODIGO)
    INNER JOIN XTIPOSAULA USING (CODIGO, ANO_LETIVO, PERIODO)
GROUP BY CURSO
HAVING COUNT(DISTINCT TIPO) = 5;


SELECT CURSO
FROM XOCORRENCIAS
    INNER JOIN XUCS USING (CODIGO)
    INNER JOIN XTIPOSAULA USING (CODIGO, ANO_LETIVO, PERIODO)
GROUP BY CURSO
HAVING COUNT(DISTINCT TIPO) = (
        SELECT COUNT(DISTINCT TIPO)
        FROM XTIPOSAULA);

-- y environment
SELECT CURSO
FROM YOCORRENCIAS
    INNER JOIN YUCS USING (CODIGO)
    INNER JOIN YTIPOSAULA USING (CODIGO, ANO_LETIVO, PERIODO)
GROUP BY CURSO
HAVING COUNT(DISTINCT TIPO) = 5;


SELECT CURSO
FROM YOCORRENCIAS
    INNER JOIN YUCS USING (CODIGO)
    INNER JOIN YTIPOSAULA USING (CODIGO, ANO_LETIVO, PERIODO)
GROUP BY CURSO
HAVING COUNT(DISTINCT TIPO) = (
        SELECT COUNT(DISTINCT TIPO)
        FROM YTIPOSAULA);

-- z environment
SELECT CURSO
FROM ZOCORRENCIAS
    INNER JOIN ZUCS USING (CODIGO)
    INNER JOIN ZTIPOSAULA USING (CODIGO, ANO_LETIVO, PERIODO)
GROUP BY CURSO
HAVING COUNT(DISTINCT TIPO) = 5;


SELECT CURSO
FROM ZOCORRENCIAS
    INNER JOIN ZUCS USING (CODIGO)
    INNER JOIN ZTIPOSAULA USING (CODIGO, ANO_LETIVO, PERIODO)
GROUP BY CURSO
HAVING COUNT(DISTINCT TIPO) = (
        SELECT COUNT(DISTINCT TIPO)
        FROM ZTIPOSAULA);
