SELECT CODIGO, DESIGNACAO, ANO_LETIVO, INSCRITOS, TIPO, TURNOS
    FROM XUCS AS ucs
        INNER JOIN XOCORRENCIAS USING(CODIGO)
        INNER JOIN XTIPOSAULAS USING (ANO_LETIVO, PERIODO, CODIGO)
    WHERE DESIGNACAO = "Base de Dados" AND CURSO = 275;

SELECT CODIGO, DESIGNACAO, ANO_LETIVO, INSCRITOS, TIPO, TURNOS
    FROM YUCS AS ucs
        INNER JOIN YOCORRENCIAS USING(CODIGO)
        INNER JOIN YTIPOSAULAS USING (ANO_LETIVO, PERIODO, CODIGO)
    WHERE DESIGNACAO = "Base de Dados" AND CURSO = 275;

SELECT CODIGO, DESIGNACAO, ANO_LETIVO, INSCRITOS, TIPO, TURNOS
    FROM ZUCS AS ucs
        INNER JOIN ZOCORRENCIAS USING(CODIGO)
        INNER JOIN ZTIPOSAULAS USING (ANO_LETIVO, PERIODO, CODIGO)
    WHERE DESIGNACAO = "Base de Dados" AND CURSO = 275;