-- Standard Constraints

-- Primary Keys
ALTER TABLE ZDOCENTES
    ADD CONSTRAINT zdocentes_pk PRIMARY KEY(NR);

ALTER TABLE ZDSD
    ADD CONSTRAINT zdsd_pk PRIMARY KEY(NR, ID);

ALTER TABLE ZTIPOSAULA
    ADD CONSTRAINT ztiposaula_pk PRIMARY KEY(ID);

ALTER TABLE ZOCORRENCIAS
    ADD CONSTRAINT zocorrencias_pk PRIMARY KEY(CODIGO, ANO_LETIVO, PERIODO);

ALTER TABLE ZUCS
    ADD CONSTRAINT zucs_pk PRIMARY KEY(CODIGO);

-- Foreign Keys
ALTER TABLE ZDSD
    ADD CONSTRAINT zdsd_nr_fk FOREIGN KEY(NR) REFERENCES ZDOCENTES(NR);

ALTER TABLE ZDSD
    ADD CONSTRAINT zdsd_id_fk FOREIGN KEY(ID) REFERENCES ZTIPOSAULA(ID);

ALTER TABLE ZTIPOSAULA
    ADD CONSTRAINT ztiposaula_fk FOREIGN KEY(ANO_LETIVO,PERIODO, CODIGO) REFERENCES YOCORRENCIAS(ANO_LETIVO, PERIODO, CODIGO);

ALTER TABLE ZOCORRENCIAS
    ADD CONSTRAINT zocorrencias_fk FOREIGN KEY(CODIGO) REFERENCES ZUCS(CODIGO);
