DROP TABLE XDOCENTES;
DROP TABLE YDOCENTES;
DROP TABLE ZDOCENTES;

DROP TABLE XDSD;
DROP TABLE YDSD;
DROP TABLE ZDSD;

DROP TABLE XOCORRENCIAS;
DROP TABLE YOCORRENCIAS;
DROP TABLE ZOCORRENCIAS;

DROP TABLE XTIPOSAULA;
DROP TABLE YTIPOSAULA;
DROP TABLE ZTIPOSAULA;

DROP TABLE XUCS;
DROP TABLE YUCS;
DROP TABLE ZUCS;