CREATE TABLE XDOCENTES AS (
    SELECT * FROM GTD10.XDOCENTES
);
CREATE TABLE YDOCENTES AS (
    SELECT * FROM GTD10.XDOCENTES
);
CREATE TABLE ZDOCENTES AS (
    SELECT * FROM GTD10.XDOCENTES
);

CREATE TABLE XDSD AS (
    SELECT * FROM GTD10.XDSD
);
CREATE TABLE YDSD AS (
    SELECT * FROM GTD10.XDSD
);
CREATE TABLE ZDSD AS (
    SELECT * FROM GTD10.XDSD
);

CREATE TABLE XOCORRENCIAS AS (
    SELECT * FROM GTD10.XOCORRENCIAS
);
CREATE TABLE YOCORRENCIAS AS (
    SELECT * FROM GTD10.XOCORRENCIAS
);
CREATE TABLE ZOCORRENCIAS AS (
    SELECT * FROM GTD10.XOCORRENCIAS
);

CREATE TABLE XTIPOSAULA AS (
    SELECT * FROM GTD10.XTIPOSAULA
);
CREATE TABLE YTIPOSAULA AS (
    SELECT * FROM GTD10.XTIPOSAULA
);
CREATE TABLE ZTIPOSAULA AS (
    SELECT * FROM GTD10.XTIPOSAULA
);

CREATE TABLE XUCS AS (
    SELECT * FROM GTD10.XUCS
);
CREATE TABLE YUCS AS (
    SELECT * FROM GTD10.XUCS
);
CREATE TABLE ZUCS AS (
    SELECT * FROM GTD10.XUCS
);