-- Standard Constraints

-- Primary Keys
ALTER TABLE ZDOCENTES
    ADD CONSTRAINT zdocentes_pk PRIMARY KEY(NR);

ALTER TABLE ZDSD
    ADD CONSTRAINT zdsd_pk PRIMARY KEY(NR, ID);

ALTER TABLE ZTIPOSAULA
    ADD CONSTRAINT ztiposaula_pk PRIMARY KEY(ID);

ALTER TABLE ZOCORRENCIAS
    ADD CONSTRAINT zocorrencias_pk PRIMARY KEY(CODIGO, ANO_LETIVO, PERIODO);

ALTER TABLE ZUCS
    ADD CONSTRAINT zucs_pk PRIMARY KEY(CODIGO);

-- Foreign Keys
ALTER TABLE ZDSD
    ADD CONSTRAINT zdsd_nr_fk FOREIGN KEY(NR) REFERENCES ZDOCENTES(NR);

ALTER TABLE ZDSD
    ADD CONSTRAINT zdsd_id_fk FOREIGN KEY(ID) REFERENCES ZTIPOSAULA(ID);

ALTER TABLE ZTIPOSAULA
    ADD CONSTRAINT ztiposaula_fk FOREIGN KEY(CODIGO, ANO_LETIVO, PERIODO) REFERENCES ZOCORRENCIAS(CODIGO, ANO_LETIVO, PERIODO);

ALTER TABLE ZOCORRENCIAS
    ADD CONSTRAINT zocorrencias_fk FOREIGN KEY(CODIGO) REFERENCES ZUCS(CODIGO);

-- Extra INDEXES
CREATE INDEX cap_idx ON ZTIPOSAULA(CODIGO, ANO_LETIVO, PERIODO);

CREATE BITMAP INDEX tipo_idx ON ZTIPOSAULA(TIPO);

CREATE INDEX ano_tp_idx ON ZTIPOSAULA(ANO_LETIVO);
CREATE INDEX ano_oc_idx ON ZOCORRENCIAS(ANO_LETIVO);

CREATE BITMAP INDEX curso_idx ON ZUCS(CURSO);

CREATE INDEX id_idx ON ZDSD(ID);